<a href="https://colab.research.google.com/github/Thousif-Mohammad/ML-DS-Projects/blob/main/Numpy%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(2, 6):
  print(i)

2
3
4
5


In [ ]:
 nums=[2,3,6,1,2,8,0]
 nums.sort()
 print(nums)
 #print(nums[0]*nums[1], nums[len(nums)-1]*nums[len(nums)-2], nums[0], nums[1], nums[len(nums)-1], nums[len(nums)-2])


[0, 1, 2, 2, 3, 6, 8]


In [ ]:
if nums[0]*nums[1] > nums[-1]*nums[-2]:
    ans = nums[0]*nums[1]
else:
    ans = nums[len(nums)-1]*nums[len(nums)-2]

print(ans)

48


In [ ]:
num=1
if num>20:
  print("old")
elif num>=10 and num<=20:
  print("btwn 10 & 20")
elif num>=2 and num <=9:
  print('btwn 2 & 9')
else:
  print('started growing')

started growing


In [ ]:


# code to test slicing
tuple1 = (0 ,1, 2, 3)

print(tuple1[1:])
print(tuple1[::-1])
print(tuple1[2:10])

(1, 2, 3)
(3, 2, 1, 0)
(2, 3)


In [ ]:
n=4
l=[3,2,1,0]
s=l[0]
l[0]=l[n-1]
l[n-1]=l[n-2]
for i in range(1, n-1):
  l[i]=s

  s=l[i+1]

for x in l:
  print(x, end=' ')

0 3 1 1 

In [ ]:
l=[3,2,1,0]
print(l[-1:], l[:-1], l[::-1], l[::-1][1:])
nl=l[-1:]+l[:-1]
print(repr(nl), type(nl))


[0] [3, 2, 1] [0, 1, 2, 3] []


0

In [ ]:
l=[3,2,1,0]
#l.sort()
for i in range(len(l)):
  for j in range(len(l)-1):
    if l[j]>l[j+1]:
      l[j], l[j+1] = l[j+1], l[j]
print(l)

[0, 1, 2, 3]


In [ ]:

    def flattenArr(ar, res):
      for x in ar:
        print(x, isinstance(x, list))
        if isinstance(x, list):
            res=flattenArr(x, res)
        else:
          res.append(x)
      return res

    arr=[[1, 2, 3], [2], [3, [4, 5]]]
    res_arr=[]
    for x in arr:
        if(type(x)==list):
            res_arr=flattenArr(x, res_arr)

        else:
            res_arr.append(x)
        res_arr.sort()
    print( res_arr)



1 False
2 False
3 False
2 False
3 False
[4, 5] True
4 False
5 False
[1, 2, 2, 3, 3, 4, 5]


In [ ]:
d={1:'s', 2:'f', 3:'g'}
type(d.values())
list(d.keys())[0]
ans1=dict(sorted(d.items(), key=lambda item:item[1]))
print(ans1)
list(ans1.keys())[0]

{2: 'f', 3: 'g', 1: 's'}


2

In [ ]:
array = [ [1, [ [ 2 ] ], [ [ [ 3 ] ] ], [ [ 4 ], 5 ] ]]
result = lambda x: sum(map(result, x), [ ] ) if isinstance(x, list) else [x]
print(result(array))

[1, 2, 3, 4, 5]


In [ ]:
from functools import reduce
array = {1, 2, 3}
result = lambda array: reduce(lambda P, x: P + [subset | {x} for subset in P], array , [set()])

print(result(array))



[set(), {1}, {2}, {1, 2}, {3}, {1, 3}, {2, 3}, {1, 2, 3}]


In [1]:
import numpy as np


In [ ]:
x = np.arange(24).reshape((2, 3, 4))
print(x)
print('----------------')
res = np.argmax(x, axis=1, keepdims=True)
print(res)
res = np.argmax(x, axis=1, keepdims=False)
#print(res)
x[res]

NameError: name 'np' is not defined

In [ ]:
ar=np.eye(3)
ar[:, 2]

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(ar[:, 2], a[:, 2])


[0. 0. 1.] [3 6 9]


In [3]:
import numpy as np
ar=[1,2,3,4,5,6]
a=[x if x%2!=0 else 0 for x in ar]
a=np.array(a)
ind=np.where(a==0)[0]
a=np.delete(a, ind)
print(a, ind)
ar=np.array(ar)
ar=ar[ar%2==0]
print(ar)


[1 3 5] [1 3 5]
[2 4 6]


In [4]:
c=np.random.rand(8,13,13)
c.shape
c

array([[[0.66656209, 0.96051836, 0.56826527, ..., 0.31275479,
         0.80269413, 0.1637408 ],
        [0.76373703, 0.29710329, 0.85265115, ..., 0.2097688 ,
         0.81169857, 0.33395157],
        [0.69008521, 0.763487  , 0.69322274, ..., 0.25556897,
         0.64300095, 0.85021512],
        ...,
        [0.40597339, 0.79257278, 0.42725616, ..., 0.55265052,
         0.14401768, 0.08224478],
        [0.00615678, 0.53927785, 0.30326973, ..., 0.33005624,
         0.6454922 , 0.30089106],
        [0.7860481 , 0.64395333, 0.83898747, ..., 0.95811815,
         0.56599111, 0.19185156]],

       [[0.41775446, 0.55451629, 0.30720449, ..., 0.33254957,
         0.95009234, 0.59302011],
        [0.10166633, 0.15334943, 0.55391739, ..., 0.0409854 ,
         0.39771241, 0.77273707],
        [0.04689009, 0.8229769 , 0.68366422, ..., 0.42007717,
         0.41571667, 0.93376148],
        ...,
        [0.95218589, 0.49009792, 0.87329257, ..., 0.76449424,
         0.10780522, 0.33490523],
        [0.9

In [9]:
import pandas as pd

data = {
    'name': ['Luffy', 'Chopper', 'Zoro', 'Sanji'],
    'marks': [15, 89, 33, 32]
}

df = pd.DataFrame(data)
df

name  marks
0    Luffy     15
1  Chopper     89
2     Zoro     33
3    Sanji     32

In [1]:
df[df['marks']>32]['name']


NameError: name 'df' is not defined

In [4]:
import pandas as pd
df1 = pd.DataFrame({"name": ['tobey', 'peter', 'chris', 'pratt'],'chem_score':[10, 9, 8, 7], 'phy_score':[7, 8, 9, 10], 'Hindi_score':[9, 9, 9, 9]})
df2 = pd.DataFrame({"name": ['chris', 'pratt', 'andrew', 'tom'],'chem_score':[10, 10, 10, 9], 'maths_score':[6, 6, 7, 9], 'eng_score':[9, 10, 10, 9]})

df1, df2

NameError: name 'df2z' is not defined

In [11]:
dfn=pd.concat([df1, df2], axis=0)
dfn

name  chem_score  phy_score  Hindi_score  maths_score  eng_score
0   tobey          10        7.0          9.0          NaN        NaN
1   peter           9        8.0          9.0          NaN        NaN
2   chris           8        9.0          9.0          NaN        NaN
3   pratt           7       10.0          9.0          NaN        NaN
0   chris          10        NaN          NaN          6.0        9.0
1   pratt          10        NaN          NaN          6.0       10.0
2  andrew          10        NaN          NaN          7.0       10.0
3     tom           9        NaN          NaN          9.0        9.0

In [22]:
dfn.isna().sum()
dfn.isna().sum().sum()
dfn.isna().any()

4

In [23]:
dfn.fillna(0)

name  chem_score  phy_score  Hindi_score  maths_score  eng_score
0   tobey          10        7.0          9.0          0.0        0.0
1   peter           9        8.0          9.0          0.0        0.0
2   chris           8        9.0          9.0          0.0        0.0
3   pratt           7       10.0          9.0          0.0        0.0
0   chris          10        0.0          0.0          6.0        9.0
1   pratt          10        0.0          0.0          6.0       10.0
2  andrew          10        0.0          0.0          7.0       10.0
3     tom           9        0.0          0.0          9.0        9.0

In [27]:
# .join happens on indexes
dfj=df1.join(df2, how='inner', lsuffix='_left', rsuffix='_right')
dfj

name_left  chem_score_left  phy_score  Hindi_score name_right  \
0     tobey               10          7            9      chris   
1     peter                9          8            9      pratt   
2     chris                8          9            9     andrew   
3     pratt                7         10            9        tom   

   chem_score_right  maths_score  eng_score  
0                10            6          9  
1                10            6         10  
2                10            7         10  
3                 9            9          9

In [29]:
# .merge happens on columns as sql inner join
dfm=df1.merge(df2, how='inner', on='name')
dfm

name  chem_score_x  phy_score  Hindi_score  chem_score_y  maths_score  \
0  chris             8          9            9            10            6   
1  pratt             7         10            9            10            6   

   eng_score  
0          9  
1         10

In [31]:
dfm.mean()

TypeError: Could not convert ['chrispratt'] to numeric

In [35]:
dfm.drop('name', axis=1)
dfm.drop('name', axis=1).mean()   #this can be done only when all the columns data of df is numeric.

chem_score_x     7.5
phy_score        9.5
Hindi_score      9.0
chem_score_y    10.0
maths_score      6.0
eng_score        9.5
dtype: float64

In [40]:
dfm.set_index('name')
dfm.set_index('name').mean(axis=1)

name
chris    8.500000
pratt    8.666667
dtype: float64